### PR TITLE
Add COinS to records and tell Zotero items are updated -- SEARCH-815.

### PR DESCRIPTION
**Pull request by jonearley**

### CODE REVIEW

**Comment by jonearley** [comment]
This is no longer going to be in release 03. Once release 04 is a thing, this should merge into that.

**Comment by jonearley** [comment]
I've merged `release_04` into master so pointing this back at master.

**Comment by bertrama** [comment]
Rebased back to release_04 (the top of release_04), hence the force push.  release_04 has commits that aren't in master.

**Comment by jonearley** [comment]
Thanks for catching that!

**Pull request merged**
